# -*- coding: utf-8 -*-
"""LDA · 电子计算征程（E1…Ex）核心包 ecore（electronic compute core）。

路线：模拟电子计算核（MVM 交叉阵列）——电子版的「光子 MZI 网格」。
E1 基座：晶体管级模型（mosfet）+ MNA 电路仿真器（mna）+ 最小模拟计算单元（analog_mvm）。
"""
from __future__ import annotations

from .analog_mvm import (
    inverting_summer,
    inverting_summer_golden,
    mosfet_saturation_bias,
    mosfet_saturation_golden,
)
from .crossbar_mvm import (
    CROSSBAR_DISCLOSURE,
    CrossbarMVM,
    build_ota_circuit,
    ota_open_loop_gain,
)
from .capability_manifest import (
    ECORE_CAPABILITY_DISCLOSURE,
    ECORE_CAPABILITY_MANIFEST,
    ecore_module_names,
    manifest_check,
)
from .mna import Circuit
from .mvm_datapath import (
    MVM_DATAPATH_DISCLOSURE,
    AnalogMvmUnit,
    MvmDatapath,
    mvm_datapath_self_check,
    quantize_uniform,
    relu,
    tiled_mvm,
)
from .scale_bench import (
    LANDMARKS,
    LDA_CAPABILITIES,
    NON_CLAIMED,
    SCALE_BENCH_DISCLOSURE,
    honest_boundary_ok,
    honest_comparison,
    scale_bench_self_check,
    scale_sweep,
)
from .mosfet import (
    MOSFET_DISCLOSURE,
    NmosParams,
    id_gm_gds,
    id_saturation_closed,
    mosfet_self_check,
    vdsat,
)
from .elayers import (
    DEFAULT_CMOS_STACK,
    ELEC_DESIGN_RULES,
    ELEC_DISCLOSURE,
    ELayer,
    ELayerStack,
    get_estack,
)
from .layout import (
    EDRC_RULES,
    LAYOUT_DISCLOSURE,
    array_footprint,
    crossbar_array,
    crosspoint_cell,
    elvs_signoff,
    expected_netlist,
    extract_wl,
    gds_roundtrip_check,
    layout_svg,
    run_edrc,
    to_gds,
)
from .parasitic import (
    ELEC_PROCESS,
    PARASITIC_DISCLOSURE,
    array_parasitics,
    build_network,
    elmore_delay,
    ideal_column_currents,
    ir_drop_report,
    solve_network,
    sneak_report,
    wire_capacitance,
    wire_resistance,
)
from .mismatch import (
    MISMATCH_DISCLOSURE,
    MISMATCH_PROCESS,
    calibration_report,
    flicker_input_noise_psd,
    flicker_output_noise_psd,
    input_referred_noise_psd,
    mc_output_error,
    mobility_ratio,
    mvm_output,
    nominal_conductances,
    pelgrom_sigma_beta_rel,
    pelgrom_sigma_vth_mv,
    sample_mismatch,
    sigma_vs_n,
    thermal_noise_psd,
    vth_at,
)
from .array_scale import (
    LANDMARKS as SCALE_LANDMARKS,
    LDA_CAPABILITIES as SCALE_LDA_CAPABILITIES,
    NON_CLAIMED as SCALE_NON_CLAIMED,
    SCALE_DISCLOSURE,
    array_scale_sweep,
    compression_ratio,
    elements_flat,
    elements_hierarchical,
    expanded_element_count,
    hierarchical_gds,
    honest_boundary_ok as scale_honest_boundary_ok,
    honest_comparison as scale_honest_comparison,
    max_scale_for_budget,
    row_line_profile,
    sigma_out_rel,
)
from .device_pde import (
    CM3_TO_M3,
    DEVICE_PDE_DISCLOSURE,
    DX_IF_NM_DEFAULT as DEVICE_PDE_DX_IF_NM,
    F_PER_UM2_TO_F_PER_M2,
    NA_CM3_DEFAULT as DEVICE_PDE_NA_CM3,
    NM_TO_M,
    T_OX_NM_DEFAULT as DEVICE_PDE_T_OX_NM,
    UM_TO_M,
    VFB_V_DEFAULT as DEVICE_PDE_VFB_V,
    cm3_to_m3,
    cox_f_per_um2_to_f_per_m2,
    cross_check_qs,
    cross_check_vth,
    device_pde_self_check,
    m3_to_cm3,
    m_to_nm,
    m_to_um,
    moscap_qs_pde,
    nm_to_m,
    parameter_consistency_report,
    pde_vs_closed_sweep,
    physics_qs_closed,
    physics_vth_closed,
    physics_vth_pde,
    um_to_m,
)
from .device_limits import (
    DEVICE_LIMITS_DISCLOSURE,
    LITERATURE_LIMITS,
    LITERATURE_PARAMS,
    N_CRIT_DEGENERATE,
    N_CRIT_NUMERICAL,
    WINDOW_HALF_WIDTH_PHI_F,
    WINDOW_REFERENCE_DX_IF_NM,
    capability_boundary_map,
    degeneracy_phi_f,
    dibl_characteristic_length,
    dibl_dvth,
    literature_gap_report,
    measure_window_edge,
    mobility_degradation_factor,
    numerical_window_grid_dependence,
    numerical_window_phi_f,
    run_selfchecks as device_limits_self_check,
    velocity_saturation_field,
    window_ratio_physical_over_numerical,
    yau_rolloff_dvth,
)

__all__ = [
    "Circuit",
    "NmosParams",
    "id_gm_gds",
    "id_saturation_closed",
    "vdsat",
    "mosfet_self_check",
    "MOSFET_DISCLOSURE",
    "inverting_summer",
    "inverting_summer_golden",
    "mosfet_saturation_bias",
    "mosfet_saturation_golden",
    "CrossbarMVM",
    "build_ota_circuit",
    "ota_open_loop_gain",
    "CROSSBAR_DISCLOSURE",
    "AnalogMvmUnit",
    "MvmDatapath",
    "quantize_uniform",
    "relu",
    "tiled_mvm",
    "mvm_datapath_self_check",
    "MVM_DATAPATH_DISCLOSURE",
    "scale_sweep",
    "scale_bench_self_check",
    "honest_comparison",
    "honest_boundary_ok",
    "LANDMARKS",
    "LDA_CAPABILITIES",
    "NON_CLAIMED",
    "SCALE_BENCH_DISCLOSURE",
    "ECORE_CAPABILITY_MANIFEST",
    "ECORE_CAPABILITY_DISCLOSURE",
    "manifest_check",
    "ecore_module_names",
    "ELayer",
    "ELayerStack",
    "DEFAULT_CMOS_STACK",
    "get_estack",
    "ELEC_DESIGN_RULES",
    "ELEC_DISCLOSURE",
    "EDRC_RULES",
    "LAYOUT_DISCLOSURE",
    "crosspoint_cell",
    "crossbar_array",
    "array_footprint",
    "expected_netlist",
    "extract_wl",
    "run_edrc",
    "elvs_signoff",
    "to_gds",
    "gds_roundtrip_check",
    "layout_svg",
    "ELEC_PROCESS",
    "PARASITIC_DISCLOSURE",
    "array_parasitics",
    "build_network",
    "elmore_delay",
    "ideal_column_currents",
    "ir_drop_report",
    "solve_network",
    "sneak_report",
    "wire_capacitance",
    "wire_resistance",
    "MISMATCH_PROCESS",
    "MISMATCH_DISCLOSURE",
    "pelgrom_sigma_vth_mv",
    "pelgrom_sigma_beta_rel",
    "vth_at",
    "mobility_ratio",
    "thermal_noise_psd",
    "flicker_input_noise_psd",
    "flicker_output_noise_psd",
    "input_referred_noise_psd",
    "nominal_conductances",
    "sample_mismatch",
    "mvm_output",
    "mc_output_error",
    "sigma_vs_n",
    "calibration_report",
    "SCALE_DISCLOSURE",
    "SCALE_LANDMARKS",
    "SCALE_LDA_CAPABILITIES",
    "SCALE_NON_CLAIMED",
    "elements_flat",
    "elements_hierarchical",
    "compression_ratio",
    "hierarchical_gds",
    "expanded_element_count",
    "row_line_profile",
    "max_scale_for_budget",
    "sigma_out_rel",
    "array_scale_sweep",
    "scale_honest_comparison",
    "scale_honest_boundary_ok",
    # E11-c 器件级内核桥（量纲桥 + 教科书闭式 ⟷ MOSCAP PDE 交叉验证）
    "UM_TO_M",
    "NM_TO_M",
    "CM3_TO_M3",
    "F_PER_UM2_TO_F_PER_M2",
    "um_to_m",
    "m_to_um",
    "nm_to_m",
    "m_to_nm",
    "cm3_to_m3",
    "m3_to_cm3",
    "cox_f_per_um2_to_f_per_m2",
    "physics_vth_closed",
    "physics_qs_closed",
    "physics_vth_pde",
    "moscap_qs_pde",
    "cross_check_vth",
    "cross_check_qs",
    "pde_vs_closed_sweep",
    "parameter_consistency_report",
    "device_pde_self_check",
    "DEVICE_PDE_DISCLOSURE",
    "DEVICE_PDE_DX_IF_NM",
    "DEVICE_PDE_NA_CM3",
    "DEVICE_PDE_T_OX_NM",
    "DEVICE_PDE_VFB_V",
    # E11-d 器件级模型失效边界（数值窗口实测 + 物理窗口文献登记 + 缺口量化）
    "N_CRIT_NUMERICAL",
    "N_CRIT_DEGENERATE",
    "WINDOW_HALF_WIDTH_PHI_F",
    "WINDOW_REFERENCE_DX_IF_NM",
    "numerical_window_phi_f",
    "degeneracy_phi_f",
    "window_ratio_physical_over_numerical",
    "measure_window_edge",
    "numerical_window_grid_dependence",
    "LITERATURE_LIMITS",
    "LITERATURE_PARAMS",
    "yau_rolloff_dvth",
    "dibl_characteristic_length",
    "dibl_dvth",
    "velocity_saturation_field",
    "mobility_degradation_factor",
    "literature_gap_report",
    "capability_boundary_map",
    "DEVICE_LIMITS_DISCLOSURE",
    "device_limits_self_check",
]

# 征程入口披露（对外引用须携此诚实边界）
ECORE_DISCLOSURE: dict = {
    "route": "模拟电子计算核（MVM 交叉阵列）：电子版的「光子 MZI 网格」。",
    "e1_scope": "E1 基座：晶体管级长沟道模型 + MNA 电路仿真器（DC/瞬态/AC）+ 最小模拟计算单元。",
    "e2_scope": "E2 参数化阵列：N×M 模拟 MVM 交叉阵列生成器（amp='ideal' VCVS TIA / amp='transistor' NMOS三极管权重）；另含晶体管级 OTA 开环增益表征。",
    "e3_scope": "E3 数据通路：数字→DAC→交叉阵列→ADC→数字 的模拟计算引擎；多层级联(MLP+ReLU)+分块(tiling)；带符号权重用参考列法映射；端到端 vs 全精度数字 golden 正确性判据。",
    "e4_scope": "E4 规模对标（诚实边界）：N×N 数据通路规模扫描(至 256×256=65536 突触) + 公开模拟加速器 landmark 诚实对标；不报 TOPS/TOPS/W；相对误差有界/绝对误差 ∝N。",
    "e5_scope": "E5 平台能力硬化：ecore 能力清单（ECORE_CAPABILITY_MANIFEST·单一真源）+ 常驻守护门禁（清单↔模块/符号双向完备 + 披露一致 + 诚实边界）。",
    "e6_scope": "E6 版图与几何签核：电子版图层栈（DIFF/POLY/CONT/M1/VIA1/M2 + 层语义谓词 + 设计规则）+ 1T 交叉阵列版图 P&R（节距闭式 + AREF 层次化）+ 几何 DRC（线宽/间距/包围/面积）+ 段感知 LVS（连通分量/短路/悬空桥/W-L 几何回提）+ 真 GDSII 出口。",
    "e7_scope": "E7 寄生提取与后仿：从 E6 版图按教科书闭式提导线 RC（R=ρL/(Wt)·C=ε₀ε_r·W/d）+ 阵列 R 梯网络（行/列分段电阻 + 交叉点电导）注入 MNA 后仿，量化 IR drop（随规模超线性增）与 sneak path（half-select 浮空方案旁路电流）+ Elmore 互连延迟；golden = 解析 I_j=Σg_ij·V_i（R=0 精确复现）。",
    "e8_scope": "E8 非理想/失配/噪声：Pelgrom 器件失配（σ_ΔVth=A_VT/√(W·L)、σ_Δβ/β）+ 温度一阶模型（Vth 线性漂移 · 迁移率 (T/T0)^m · 片内列热梯度）+ 噪声（热 4kTγg_m · 闪烁 K_f/(C_ox·W·L·f)）+ 失配 Monte Carlo 输出误差分布（自证 σ_rel ∝ 1/√N）+ 校准层级 L0 原始 / L1 列增益 / L2 逐单元。",
    "e9_scope": "E9 规模压力与诚实对标：E6 物化版图与 E7 稠密 MNA 都只到 N≈32 ⇒ 换 O(N) 算法（cell+AREF 层次化出图 + 一维三对角 IR-drop 求解）推到千级阵列；三重规模律（IR drop 超线性 · 面积 ∝N² · 失配 σ ∝1/√N · Elmore ∝N²）+ 按误差预算反解可及规模上界 + 同族维度诚实对标（landmark 照录·不报 TOPS）。",
    "e10_scope": "E10 收官（平台硬化 + 案例卡升级 + 对外物料 + 生产部署）：把 E1–E9 全链固化为**对外只读案例卡**（`/api/ecore_demo` · 九段里程碑 + 四块新能力面 facts + 9 条诚实边界）+ 守护 scope 扩到本段 + 对外物料与生产上线；本段**不新增求解器能力**，属集成/对外/验收段（新增判据由 run_ecore_case_smoke 承载）。",
    "e11_scope": "E11 器件级内核接线：**E11-a** 口径同步（把「本包的设计取舍」与「平台红线」两件事分离，统一订正为**分层口径** + 防漂移门禁）；**E11-b** 接缝勘查（查明 ecore 与器件级内核零复用的根因 = 两侧非同一器件：`drift_diffusion_1d/2d` 是两端 p-n 结，本包要的是三端 MOSFET）；**E11-c 器件级内核桥** = 平台新增 MOS 结构 1D 自洽泊松内核（`lda_solver/mos_1d.py` · MOSCAP）+ 本包 `device_pde.py`：量纲桥（SI ⟷ µm 制）+ 教科书闭式（Sze 完整 Q_s 式 / 耗尽近似 V_th 式）⟷ PDE 数值解交叉验证（V_th 与 Q_s 跨点一致 ≤0.02% · 工作区 ψ_s ≤ 2.5φ_F）+ 参数自洽性显式报告（G-3）。🔴 golden = 教科书闭式，PDE 只是 candidate（`is_oracle=False`）；**不替换**任何电路级默认参数（`NmosParams` 逐位不变）。**E11-d 失效边界测绘** = `device_limits.py`：**两类边界严格分离** —— A **数值窗口**（LDA 实测：ψ_s ∈ φ_F·[1±1.54]，**随网格变化**：0.05→0.02 nm 时窗口变宽）/ B **物理窗口**（文献判据：玻尔兹曼简并 + 1D 无源漏，**与网格无关**）⇒ **物理模型先失效、数值后崩**（半宽比 0.835）；另含文献经验式**缺口量化**（L=65 nm 时短沟道 roll-off 占 V_th **37.9%**）· 每项标 `computed_by_lda=False`。",
    "redline": "红线 = **分层口径**（2026-09-11 §八§九 · 2026-09-23 逐步解锁）：平台**器件级 T1 内核已解锁**"
               "（`lda_solver/drift_diffusion_1d/2d`）；**T2 工艺真值 / 工艺角 / 流片永久锁**。"
               "**本包主动限定在电路级**——这是设计取舍，不是红线要求。",
    "sovereignty": "C 级自主（纯 numpy），不借 HSPICE/Spectre 等商业 SPICE 引擎；LLM 不进判决路径。",
    "honest_boundary": "电路级设计验证引擎，非签核级 SPICE（无温度/噪声/稀疏矩阵/收敛增强）；"
                       "晶体管参数为公开典型量级占位，非 PDK 标定，无实测锚 ⇒ 不宣称器件性能。",
    "not_oracle": "golden 均为闭式物理律（分压/平方律/一阶 RC）；不引入任何外部 ORACLE。",
}
