# -*- coding: utf-8 -*-
"""LDA · 电子计算征程（E1…Ex）核心包 ecore（electronic compute core）。

路线：模拟电子计算核（MVM 交叉阵列）——电子版的「光子 MZI 网格」。
E1 基座：晶体管级模型（mosfet）+ MNA 电路仿真器（mna）+ 最小模拟计算单元（analog_mvm）。
"""
from __future__ import annotations

from .analog_mvm import (
    inverting_summer,
    inverting_summer_golden,
    mosfet_saturation_bias,
    mosfet_saturation_golden,
)
from .crossbar_mvm import (
    CROSSBAR_DISCLOSURE,
    CrossbarMVM,
    build_ota_circuit,
    ota_open_loop_gain,
)
from .capability_manifest import (
    ECORE_CAPABILITY_DISCLOSURE,
    ECORE_CAPABILITY_MANIFEST,
    ecore_module_names,
    manifest_check,
)
from .mna import Circuit
from .mvm_datapath import (
    MVM_DATAPATH_DISCLOSURE,
    AnalogMvmUnit,
    MvmDatapath,
    mvm_datapath_self_check,
    quantize_uniform,
    relu,
    tiled_mvm,
)
from .scale_bench import (
    LANDMARKS,
    LDA_CAPABILITIES,
    NON_CLAIMED,
    SCALE_BENCH_DISCLOSURE,
    honest_boundary_ok,
    honest_comparison,
    scale_bench_self_check,
    scale_sweep,
)
from .mosfet import (
    MOSFET_DISCLOSURE,
    NmosParams,
    id_gm_gds,
    id_saturation_closed,
    mosfet_self_check,
    vdsat,
)
from .elayers import (
    DEFAULT_CMOS_STACK,
    ELEC_DESIGN_RULES,
    ELEC_DISCLOSURE,
    ELayer,
    ELayerStack,
    get_estack,
)
from .layout import (
    EDRC_RULES,
    LAYOUT_DISCLOSURE,
    array_footprint,
    crossbar_array,
    crosspoint_cell,
    elvs_signoff,
    expected_netlist,
    extract_wl,
    gds_roundtrip_check,
    layout_svg,
    run_edrc,
    to_gds,
)
from .parasitic import (
    ELEC_PROCESS,
    PARASITIC_DISCLOSURE,
    array_parasitics,
    build_network,
    elmore_delay,
    ideal_column_currents,
    ir_drop_report,
    solve_network,
    sneak_report,
    wire_capacitance,
    wire_resistance,
)
from .mismatch import (
    MISMATCH_DISCLOSURE,
    MISMATCH_PROCESS,
    calibration_report,
    flicker_input_noise_psd,
    flicker_output_noise_psd,
    input_referred_noise_psd,
    mc_output_error,
    mobility_ratio,
    mvm_output,
    nominal_conductances,
    pelgrom_sigma_beta_rel,
    pelgrom_sigma_vth_mv,
    sample_mismatch,
    sigma_vs_n,
    thermal_noise_psd,
    vth_at,
)
from .array_scale import (
    LANDMARKS as SCALE_LANDMARKS,
    LDA_CAPABILITIES as SCALE_LDA_CAPABILITIES,
    NON_CLAIMED as SCALE_NON_CLAIMED,
    SCALE_DISCLOSURE,
    array_scale_sweep,
    compression_ratio,
    elements_flat,
    elements_hierarchical,
    expanded_element_count,
    hierarchical_gds,
    honest_boundary_ok as scale_honest_boundary_ok,
    honest_comparison as scale_honest_comparison,
    max_scale_for_budget,
    row_line_profile,
    sigma_out_rel,
)

__all__ = [
    "Circuit",
    "NmosParams",
    "id_gm_gds",
    "id_saturation_closed",
    "vdsat",
    "mosfet_self_check",
    "MOSFET_DISCLOSURE",
    "inverting_summer",
    "inverting_summer_golden",
    "mosfet_saturation_bias",
    "mosfet_saturation_golden",
    "CrossbarMVM",
    "build_ota_circuit",
    "ota_open_loop_gain",
    "CROSSBAR_DISCLOSURE",
    "AnalogMvmUnit",
    "MvmDatapath",
    "quantize_uniform",
    "relu",
    "tiled_mvm",
    "mvm_datapath_self_check",
    "MVM_DATAPATH_DISCLOSURE",
    "scale_sweep",
    "scale_bench_self_check",
    "honest_comparison",
    "honest_boundary_ok",
    "LANDMARKS",
    "LDA_CAPABILITIES",
    "NON_CLAIMED",
    "SCALE_BENCH_DISCLOSURE",
    "ECORE_CAPABILITY_MANIFEST",
    "ECORE_CAPABILITY_DISCLOSURE",
    "manifest_check",
    "ecore_module_names",
    "ELayer",
    "ELayerStack",
    "DEFAULT_CMOS_STACK",
    "get_estack",
    "ELEC_DESIGN_RULES",
    "ELEC_DISCLOSURE",
    "EDRC_RULES",
    "LAYOUT_DISCLOSURE",
    "crosspoint_cell",
    "crossbar_array",
    "array_footprint",
    "expected_netlist",
    "extract_wl",
    "run_edrc",
    "elvs_signoff",
    "to_gds",
    "gds_roundtrip_check",
    "layout_svg",
    "ELEC_PROCESS",
    "PARASITIC_DISCLOSURE",
    "array_parasitics",
    "build_network",
    "elmore_delay",
    "ideal_column_currents",
    "ir_drop_report",
    "solve_network",
    "sneak_report",
    "wire_capacitance",
    "wire_resistance",
    "MISMATCH_PROCESS",
    "MISMATCH_DISCLOSURE",
    "pelgrom_sigma_vth_mv",
    "pelgrom_sigma_beta_rel",
    "vth_at",
    "mobility_ratio",
    "thermal_noise_psd",
    "flicker_input_noise_psd",
    "flicker_output_noise_psd",
    "input_referred_noise_psd",
    "nominal_conductances",
    "sample_mismatch",
    "mvm_output",
    "mc_output_error",
    "sigma_vs_n",
    "calibration_report",
    "SCALE_DISCLOSURE",
    "SCALE_LANDMARKS",
    "SCALE_LDA_CAPABILITIES",
    "SCALE_NON_CLAIMED",
    "elements_flat",
    "elements_hierarchical",
    "compression_ratio",
    "hierarchical_gds",
    "expanded_element_count",
    "row_line_profile",
    "max_scale_for_budget",
    "sigma_out_rel",
    "array_scale_sweep",
    "scale_honest_comparison",
    "scale_honest_boundary_ok",
]

# 征程入口披露（对外引用须携此诚实边界）
ECORE_DISCLOSURE: dict = {
    "route": "模拟电子计算核（MVM 交叉阵列）：电子版的「光子 MZI 网格」。",
    "e1_scope": "E1 基座：晶体管级长沟道模型 + MNA 电路仿真器（DC/瞬态/AC）+ 最小模拟计算单元。",
    "e2_scope": "E2 参数化阵列：N×M 模拟 MVM 交叉阵列生成器（amp='ideal' VCVS TIA / amp='transistor' NMOS三极管权重）；另含晶体管级 OTA 开环增益表征。",
    "e3_scope": "E3 数据通路：数字→DAC→交叉阵列→ADC→数字 的模拟计算引擎；多层级联(MLP+ReLU)+分块(tiling)；带符号权重用参考列法映射；端到端 vs 全精度数字 golden 正确性判据。",
    "e4_scope": "E4 规模对标（诚实边界）：N×N 数据通路规模扫描(至 256×256=65536 突触) + 公开模拟加速器 landmark 诚实对标；不报 TOPS/TOPS/W；相对误差有界/绝对误差 ∝N。",
    "e5_scope": "E5 平台能力硬化：ecore 能力清单（ECORE_CAPABILITY_MANIFEST·单一真源）+ 常驻守护门禁（清单↔模块/符号双向完备 + 披露一致 + 诚实边界）。",
    "e6_scope": "E6 版图与几何签核：电子版图层栈（DIFF/POLY/CONT/M1/VIA1/M2 + 层语义谓词 + 设计规则）+ 1T 交叉阵列版图 P&R（节距闭式 + AREF 层次化）+ 几何 DRC（线宽/间距/包围/面积）+ 段感知 LVS（连通分量/短路/悬空桥/W-L 几何回提）+ 真 GDSII 出口。",
    "e7_scope": "E7 寄生提取与后仿：从 E6 版图按教科书闭式提导线 RC（R=ρL/(Wt)·C=ε₀ε_r·W/d）+ 阵列 R 梯网络（行/列分段电阻 + 交叉点电导）注入 MNA 后仿，量化 IR drop（随规模超线性增）与 sneak path（half-select 浮空方案旁路电流）+ Elmore 互连延迟；golden = 解析 I_j=Σg_ij·V_i（R=0 精确复现）。",
    "e8_scope": "E8 非理想/失配/噪声：Pelgrom 器件失配（σ_ΔVth=A_VT/√(W·L)、σ_Δβ/β）+ 温度一阶模型（Vth 线性漂移 · 迁移率 (T/T0)^m · 片内列热梯度）+ 噪声（热 4kTγg_m · 闪烁 K_f/(C_ox·W·L·f)）+ 失配 Monte Carlo 输出误差分布（自证 σ_rel ∝ 1/√N）+ 校准层级 L0 原始 / L1 列增益 / L2 逐单元。",
    "e9_scope": "E9 规模压力与诚实对标：E6 物化版图与 E7 稠密 MNA 都只到 N≈32 ⇒ 换 O(N) 算法（cell+AREF 层次化出图 + 一维三对角 IR-drop 求解）推到千级阵列；三重规模律（IR drop 超线性 · 面积 ∝N² · 失配 σ ∝1/√N · Elmore ∝N²）+ 按误差预算反解可及规模上界 + 同族维度诚实对标（landmark 照录·不报 TOPS）。",
    "e10_scope": "E10 收官（平台硬化 + 案例卡升级 + 对外物料 + 生产部署）：把 E1–E9 全链固化为**对外只读案例卡**（`/api/ecore_demo` · 九段里程碑 + 四块新能力面 facts + 9 条诚实边界）+ 守护 scope 扩到本段 + 对外物料与生产上线；本段**不新增求解器能力**，属集成/对外/验收段（新增判据由 run_ecore_case_smoke 承载）。",
    "redline": "电域→仅电路级（T1）：不碰 Foundry TCAD / 工艺角 / 流片（属 T2 真值，永久锁）。",
    "sovereignty": "C 级自主（纯 numpy），不借 HSPICE/Spectre 等商业 SPICE 引擎；LLM 不进判决路径。",
    "honest_boundary": "电路级设计验证引擎，非签核级 SPICE（无温度/噪声/稀疏矩阵/收敛增强）；"
                       "晶体管参数为公开典型量级占位，非 PDK 标定，无实测锚 ⇒ 不宣称器件性能。",
    "not_oracle": "golden 均为闭式物理律（分压/平方律/一阶 RC）；不引入任何外部 ORACLE。",
}
